language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install coveralls"
script:
  - "python runtests.py tests"
  - "coverage run --source=confy runtests.py tests"
after_success:
  - coveralls
