language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - "pip install pytest --use-mirrors"
  - "pip install coveralls --use-mirrors"
script:
  - "python runtests.py tests"
  - "coverage run --source=confy runtests.py tests"
after_success:
  - coveralls
